# Generated by Django 4.0.1 on 2022-01-31 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prueba',
            options={'ordering': ['titulo'], 'verbose_name': 'Mi Pruebas', 'verbose_name_plural': 'Todas las pruebas'},
        ),
        migrations.AlterUniqueTogether(
            name='prueba',
            unique_together={('titulo', 'subtile')},
        ),
    ]
